### PR TITLE
Run post-install chmods only once

### PR DESCRIPTION
**Pull request by MauPalantir**
It checks if the mermedit group exists. I tried with files but ran into weird problems, so that's another approach I've come up with.

### CODE REVIEW

**Comment by peterstadler** [comment]
Hi @MauPalantir , could you provide a little bit more context, please?
The PR looks technically ok, but I'd like to know which issue it addresses. If it's just about the group, why not add the check `sm:list-groups() = 'mermedit'` to the `local:create-group()` function?

If it's about preserving user/group settings in general, we might want to move the `local:set-admin-password()` into the conditional execution (on first-run only) as well.

**Comment by simar0at** [comment]
I also think we should have a longer on-first-run function. We may also need to copy/move the data contents somewhere else.

**Review by simar0at — APPROVED** [review]
Looks good to me.

**Review by peterstadler — CHANGES_REQUESTED** [review]
This PR got tainted by changes related to #59 (#37) and should (can?) not be merged individually anymore? 

I think we could
a) remove the unrelated changes (to the data dir and to `local:change-group()`) or
b) delete this PR and focus on #59 (which incorporates the changes here)

**Pull request closed without merging**
