### PR TITLE
replace XML link in the forms top nav 

### PR DESCRIPTION
**Pull request by peterstadler**
to point at the "raw" MEI file, not the filtered version, implementing #177.

This PR introduces a new parameter in `filter/xsl/mermeid_configuration.xsl` which can be read by the XForms as `instance('parameters')/dcm:view_xml_url_base`. The parameter is injected on the XQuery side by `modules/transform.xq` which is called by the controller at e.g. https://github.com/Edirom/MerMEId/blob/21f7710ece19b8fe5bd1bce1045cab9539f6c0ed/data/controller.xql#L92

### CODE REVIEW

**Review by peterprovaznik — COMMENTED** [review]
I have found changing `@href` in `forms/include/topmenu.xml` to be sufficient, please verify.

```diff
diff --git a/forms/includes/topmenu.xml b/forms/includes/topmenu.xml
index 895833c0..110af348 100644
--- a/forms/includes/topmenu.xml
+++ b/forms/includes/topmenu.xml
@@ -29,7 +29,7 @@
       class="xforms-trigger" 
       target="view_{instance('parameters')/dcm:xml_file}"><h:img 
         src="{instance('parameters')/dcm:server_name}/editor/images/html.gif" alt="HTML" title="View as HTML" border="0"/></h:a><h:a 
-      href="{instance('parameters')/dcm:server_name}{instance('parameters')/dcm:document_root}{instance('parameters')/dcm:xml_file}"
+      href="{instance('parameters')/dcm:server_name}{instance('parameters')/dcm:document_root}read?filename={instance('parameters')/dcm:xml_file}"
       class="xforms-trigger" 
       target="xml_{instance('parameters')/dcm:xml_file}"><h:img 
         src="{instance('parameters')/dcm:server_name}/editor/images/xml.gif" alt="XML" title="View XML data" border="0"/></h:a><xf:trigger appearance="minimal">
```

**Comment by peterstadler** [comment]
Thanks for the hint @peterprovaznik , that looks promising and much simpler 👍

**Comment by peterstadler** [comment]
When eventually merging this PR please squash and merge to get rid of the first attempt and its reversion …

**Review by peterprovaznik — APPROVED** [review]
I have pulled the `issue-177` image, and verified that the unfiltered XML is indeed shown.

(When trying this for one of the sample-files, I noticed two `xml-model` PIs; these disappeared after making changes, which is most likely is due to PIs not being considered in `filter_{get,put}.xsl`, so related to #90.)

**Comment by peterstadler** [comment]
> I have pulled the `issue-177` image, and verified that the unfiltered XML is indeed shown.
> 
> (When trying this for one of the sample-files, I noticed two `xml-model` PIs; these disappeared after making changes, which is most likely is due to PIs not being considered in `filter_{get,put}.xsl`, so related to #90.)

Thanks for reviewing! I added the PIs to the list at #90 ;)

**Pull request merged**
