### PR TITLE
add CRUD module and API endpoints

### LINKED ISSUE #92: Copy button does not work
Clicking on copy button seems to trigger an action, but nothing seems to happen

copy-bug

### PR DESCRIPTION
**Pull request by peterstadler**
This started with the broken "copy" button (closes #92) and resulted in a major rewrite of some basic CRUD functions.
There is still a lot that can be improved, but I think it's already an improvement as it is.

Changes so far:
* add new module "crud.xqm" with public functions `crud:read`, `crud:copy`,  `crud:create`, and `crud:delete` 
* add new endpoints "/data/read", "/data/delete",  "/data/copy", "/data/rename", and  "/data/create" that use these new functions. NB, these endpoints do not feature MerMEId specific authentication but rather rely on the standard eXist permissions. E.g., an admin user (with the dba role) might add and delete data, not only the mermeid user. 
* the new endpoint "/data/read" outputs unfiltered XML and is used for displaying the MEI files to the user on request (see #90). The old endpoints in "/data/controller.xql" for Orbeon have been retained so far.
* add new module "common.xqm" to store common functions and queries.
* align the markup of the "buttons" on the main list page. They are now all `<button>` elements within a `<form>` to facilitate consistent capturing of events, styling, etc.
* remove the javascript `prompt` with more elaborate modal. The modal grabs all information from the original form on the main list page.

### CODE REVIEW

**Comment by daniel-jettka** [comment]
Questions:

1. on "Copy" and "Rename" got following error with all users I know. Is it expected?
  - `failed to create file: Write permission is not granted on the Collection. XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection.`
2. on "Edit", then changing main title and save, got following error. To do with above?
  - `Submission response status: 500 Error type: resource-error URI: http://127.0.0.2:8080/apps/mermeid/data/incipit_demo.xml Headers: DateMon, 21 Feb 2022 19:33:44 GMT `

**Comment by peterstadler** [comment]
> Questions:
> 
> 1. on "Copy" and "Rename" got following error with all users I know. Is it expected?
> 
> * `failed to create file: Write permission is not granted on the Collection. XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection.`
> 
> 2. on "Edit", then changing main title and save, got following error. To do with above?
> 
> * `Submission response status: 500 Error type: resource-error URI: http://127.0.0.2:8080/apps/mermeid/data/incipit_demo.xml Headers: DateMon, 21 Feb 2022 19:33:44 GMT`

Looks as if you're not logged in properly?
Can you try to 
1. login  as mermeid
2. click "copy" (on any entry) on the main "modules/list_files.xq" page

That should present you with a (new) modal where you can add a title and filename. Once you hit "copy" on that modal's submit button you are redirected to the list page again and your copy should show up.

**Comment by peterstadler** [comment]
Another caveat: all endpoints (except "/data/read") only accept POST requests!

**Comment by daniel-jettka** [comment]
> Looks as if you're not logged in properly? Can you try to
> 
>     1. login  as mermeid
> 
>     2. click "copy" (on any entry) on the main "modules/list_files.xq" page
> 
> 
> That should present you with a (new) modal where you can add a title and filename. Once you hit "copy" on that modal's submit button you are redirected to the list page again and your copy should show up.

- pulled all new changes from branch issue-92
- built new docker, started and logged in as mermeid
- clicked on Copy (also after triggering onfocus)

Screenshot_2022-02-22 All documents

**Comment by daniel-jettka** [comment]
> checking "Remember me" is causing trouble. Once you uncheck it, it should work. 

Yes, it does work with "Remember me" unchecked. Can confirm the CRUD actions are successful, but one has to login again after every one.

**Review by daniel-jettka — APPROVED** [review]
Tested the functionality and all buttons/options work like they're supposed to.

Only (separate) things:
* the "Remember me" option in the login procedure does not work properly

**Pull request merged**
