### PR TITLE
Fixed some graphic bugs in input mask/forms

### PR DESCRIPTION
**Pull request by daniel-jettka**

### CODE REVIEW

**Comment by AnastasiaWawilow** [comment]
I have tested. There are still a few problems left, see screenshots. 
Bildschirmfoto 2021-07-02 um 11 25 26

Bildschirmfoto 2021-07-02 um 11 36 18

Bildschirmfoto 2021-07-02 um 11 30 16

Bildschirmfoto 2021-07-02 um 11 29 03

Bildschirmfoto 2021-07-02 um 11 33 30

Bildschirmfoto 2021-07-02 um 11 30 52

**Comment by daniel-jettka** [comment]
> I have tested. There are still a few problems left, see screenshots.

The issue with the "question mark bubbles" is universal, so I created a separate issue for it: #68

**Comment by daniel-jettka** [comment]
Some other graohical issues were found during the review.

These are listed in #39 and #68

Will close this pull request for now and open another for #39 when the others are fixed too.

**Comment by peterstadler** [comment]
Just curious: why not leave this PR open and add more commits to it?

**Comment by daniel-jettka** [comment]
Apart from one problem listed above (and now in #80) all graphical displacements from #39 should be fixed now.

**Review by peterstadler — APPROVED** [review]
Looks much better now, many thanks!

**Pull request merged**
