### PR TITLE
Issue 80 - Displaced buttons in input mask 

### PR DESCRIPTION
**Pull request by daniel-jettka**
replaced the CSS bubbles with image; not always perfectly positioned but better than before

### CODE REVIEW

**Comment by daniel-jettka** [comment]
Checked the appearance again and I think we should merge this individual one in now.

**Comment by daniel-jettka** [comment]
To check: browser compatibility - looks good in my Firefox and Chrome on Linux

**Review by peterstadler — CHANGES_REQUESTED** [review]
Looks good to me (briefly tested in Firefox, Chrome and Safari on a Mac), yet there is one help icon on the main list page that you missed ;)
https://github.com/Edirom/MerMEId/blob/d294ba6529d4a27aca6b743645de47234199521b/modules/list_files.xq#L219 and the respective CSS at https://github.com/Edirom/MerMEId/blob/d294ba6529d4a27aca6b743645de47234199521b/resources/css/list_style.css#L277
In particular, it has a very ugly border …

**Review by peterstadler — APPROVED** [review]
Tested locally, looks good!
Many thanks!

**Pull request merged**
