### PR TITLE
update database variable

### LINKED ISSUE #186: fix tools for generating indexes
those tools mentioned in the help section https://github.com/Edirom/MerMEId/blob/develop/manual/index_tools.html need to be revised, see report by @gucl-mu in #181

### PR DESCRIPTION
**Pull request by peterstadler**
and update output options to fix #186

### CODE REVIEW

**Comment by peterprovaznik** [comment]
With the caveat that I don't really feel qualified to assess the quality and correctness of the output, it mostly looks good using the `issue-186` image. I have tried all the queries listed on the help page and they do result in output that looks plausible. However ...
- `location_index.xq` errors ("string concatenation operator is not available before XQuery 3.0 [at line 24, column 32 ...]"), most likely due to the use of `||` in a file that declares version 1.0 of XQuery
- images in `list_incipit_graphics.xq` are not shown correctly due to a missing `../` (`` works when I change it in DevTools)
- the help file mentions `http://my_server_name.org/storage/tools/title_index?c=CNW` at the top when it should be `modules` rather than `storage`; also I had to use `?c=Demo` to get results, might consider changing that as well.

**Comment by peterstadler** [comment]
Many thanks @peterprovaznik again for the thorough review! 
I addressed and fixed the issues in my latest commits – would you mind to have another look?

While most fixes are straight forward the latest (167618c) introduces some more changes since I realized that the failing query could be rewritten to simplify things thanks to XQuery-3.0 "group by". Yet, I'm not 100% sure what the desired result is and whether I was able to reproduce it…

**Comment by peterprovaznik** [comment]
Looks good. As for the `location_index.xq`, which contains the group-by, I get the following output:

Screenshot from 2024-01-15 17-27-51

I would understand these numbers to be all the entries in the Demo collection (`<work>/<identifier label="Demo">`) which have this location, so it would probably be better to have each identifier only once. (I think this could be achieved with something like `return $numbers => distinct-values() => string-join(', ')` in line 102.) What do you think?

**Comment by peterstadler** [comment]
many thanks for the improvement @peterprovaznik ! I just pushed it and now looks much cleaner: 

Bildschirmfoto 2024-01-15 um 22 12 45

**Review by peterprovaznik — APPROVED** [review]
As far as I can tell the index queries now work as described on the help page.

**Pull request merged**
