### PR TITLE
Display version and git revision

### PR DESCRIPTION
**Pull request by simar0at**
Please review and merge asap. Thanks in advance.

### CODE REVIEW

**Comment by simar0at** [comment]
`docker pull edirom/mermeid:display-version-and-git-revision`

**Review by dasch124 — COMMENTED** [review]
looks good and works for me – we only need to use sensible tags from now on because 2019.1 is slightly misleading ;-) 

thank also for single-sourcing the footer! Only caveat: list_files.xq doesn't seem to use the new footer – ideally we could have this fixed with this PR as well

**Comment by simar0at** [comment]
Pushed such a tag to this branch. VSCode does not push tags by default and I didn't see an option for that. TortoiseGit has an option for that. `git push origin --tags` or `git push origin <some_tag>` is an alternative.

**Review by peterstadler — COMMENTED** [review]
Let's see whether I get this right, but this is basically two things:
a) extract the version information during build from Git and push it to the running application
b) inject the version information into various html pages

I think for a) the proper (more 'existish') place would be the `expath-pkg.xml`. That seems not much of a change and would stick more to the EXPath standard.
For b) I'm not sure, but it feels a little bit like doing our own templating system. Why not just use the templating module from eXist?

**Comment by peterstadler** [comment]
Just looked at this PR with @Anastastasia and @daniel-jettka and we noticed two things that might need to be documented somewhere:

1. The Version info string is quite verbose ("2.0.0-alpha.1-6-gdaafbefa") which is great for development setups but might be a little chatty for production releases?
2. The implemented templating is a mere string replacement which is not so "XMLy" (and needs serialising and subsequent parsing of every page). 

Nevertheless, we agree to merge this PR :)

**Comment by simar0at** [comment]
ad 1. The string gets more or less verbose depending on our tagging disciplin. If we tag with only a short version string, say `2.0` and _do not_ push additional changes afterwards and silently release that the version string will be exactly `2.0`. So this is by design. The more we deviate from good practices the uglier that string gets.
ad 2. we should optimize when we see a performance problem or when the development experience is bad. I see no good alternatives right now.

**Pull request merged**
